// import 'server-only';
// import type { Metadata } from 'next';

// import { LayoutProps } from '@/types/app';

// import './globals.css';
// import { Box, Container } from '@mui/material';

// export const metadata: Metadata = {
// 	title: 'My Blog',
// 	description: 'Generated by create next app',
// };

// export default function RootLayout({ children }: LayoutProps) {
// 	return (
// 		<html lang="en">
// 			<Container maxWidth="md">
// 				<Box sx={{ padding: 4 }}>{children}</Box>
// 			</Container>
// 		</html>
// 	);
// }
import React from 'react';
import { Container, Box } from '@mui/material';

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<Container maxWidth="md">
			<Box sx={{ padding: 4 }}>{children}</Box>
		</Container>
	);
};

export default Layout;
